package com.sap.xi.xi.demo.agency;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "FlightSeatAvailabilityQuery_Out_new", targetNamespace = "http://sap.com/xi/XI/Demo/Agency")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface FlightSeatAvailabilityQueryOutNew {

  /**
   * Java representation of web method [FlightSeatAvailabilityQuery_Out].
   */
  @javax.jws.WebMethod(operationName = "FlightSeatAvailabilityQuery_Out", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "FlightSeatAvailabilityResponse", targetNamespace = "http://sap.com/xi/XI/Demo/Airline", partName = "FlightSeatAvailabilityResponse")
  public com.sap.xi.xi.demo.agency.FlightSeatAvailabilityResponse flightSeatAvailabilityQueryOut(@javax.jws.WebParam(name = "FlightSeatAvailabilityQuery", targetNamespace = "http://sap.com/xi/XI/Demo/Airline", partName = "FlightSeatAvailabilityQuery") com.sap.xi.xi.demo.agency.FlightSeatAvailabilityQuery flightSeatAvailabilityQuery) throws com.sap.xi.xi.demo.agency.FlightNotFound;

}
