package com.sap.xi.xi.demo.agency;

/**
 * Service implementation of {FlightSeatAvailabilityQuery_Out_new_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "FlightSeatAvailabilityQuery_Out_new_Service", targetNamespace = "http://sap.com/xi/XI/Demo/Agency", wsdlLocation = "wsdl/com/sap/xi/xi/demo/agency/FlightSeatAvailabilityQuery_Out_new/FlightSeatAvailabilityQuery_Out_new.wsdl")
public class FlightSeatAvailabilityQueryOutNewService extends javax.xml.ws.Service {

  private final static java.net.URL FLIGHTSEATAVAILABILITYQUERYOUTNEWSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = FlightSeatAvailabilityQueryOutNewService.class.getClassLoader().getResource("wsdl/com/sap/xi/xi/demo/agency/FlightSeatAvailabilityQuery_Out_new/FlightSeatAvailabilityQuery_Out_new.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    FLIGHTSEATAVAILABILITYQUERYOUTNEWSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public FlightSeatAvailabilityQueryOutNewService() throws java.net.MalformedURLException {
    super(FLIGHTSEATAVAILABILITYQUERYOUTNEWSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/XI/Demo/Agency", "FlightSeatAvailabilityQuery_Out_new_Service"));
  }
  public FlightSeatAvailabilityQueryOutNewService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [FlightSeatAvailabilityQuery_Out_new_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "FlightSeatAvailabilityQuery_Out_new_Port")
  public com.sap.xi.xi.demo.agency.FlightSeatAvailabilityQueryOutNew getFlightSeatAvailabilityQuery_Out_new_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/XI/Demo/Agency","FlightSeatAvailabilityQuery_Out_new_Port");
    return (com.sap.xi.xi.demo.agency.FlightSeatAvailabilityQueryOutNew) super.getPort(portName,com.sap.xi.xi.demo.agency.FlightSeatAvailabilityQueryOutNew.class);
  }
}
